version: '3.7'

services:
  flask:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump
      - ./datos_db:/data/db
